services:

  traefik:
    image: traefik:v3.7
    command:
      - "--api.insecure=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
      - "--log.level=INFO"
    ports:
      - "81:80"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ctn-local
    user: "0:0"
    deploy:
      placement:
        constraints:
          - node.hostname == kmw-20hgs0cl00

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - ctn-local
    deploy:
      placement:
        constraints:
          - node.hostname == kmw-20hgs0cl00
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mailpit.rule=Host(`mailpit.localhost`)"
        - "traefik.http.routers.mailpit.entrypoints=web"
        - "traefik.http.services.mailpit.loadbalancer.server.port=8025"

networks:
  ctn-local:
    driver: overlay
    attachable: true
