tunnel: e7fbc420-297a-4fa6-922f-c8e2e0239cee
credentials-file: /home/user/.cloudflared/e7fbc420-297a-4fa6-922f-c8e2e0239cee.json
ingress:
  - hostname: exe.caltek.net
    service: http://localhost:8084
  - hostname: caltek.net
    path: /slides
    service: http://localhost:8085
  - hostname: portainer.caltek.net
    service: http://localhost:9000
  - service: http_status:404
